version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./api_gateway:/var/www/app/
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: uvicorn api_gateway.asgi:application --host 0.0.0.0 --port 8000
    expose:
      - 8000
    volumes:
      - ./api_gateway/:/usr/src/app/
    env_file:
      - ./api_gateway/.env